version: 2.1

jobs:
  build:
    machine:
      image: buntu-2204:current
    steps:
      - checkout
      - run:
          name: Start Redis Services
          command: docker-compose up -d
      - run:
          name: Verify Redis Container is Running
          command: docker ps --filter "name=redis"
      - run:
          name: Verify Redis-SSL Container is Running
          command: docker ps --filter "name=redis-ssl"
